apiVersion: v1
name: bugzilla
description: Bugzilla bug tracking system
version: 1.0.2
appVersion: 5.0.6
keywords:
  - bugzilla
  - bug tracking
  - issue tracking
home: https://bugzilla.org
icon: https://upload.wikimedia.org/wikipedia/commons/7/7e/Buggie_new.png
sources:
  - https://github.com/bugzilla/bugzilla
maintainers:
  - name: MoJaB
    email: hello@mojab.org
engine: gotpl
