apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bugzilla.fullname" . }}
  labels:
    app: "{{ template "bugzilla.fullname" . }}"
    chart: "{{ template "bugzilla.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if .Values.bugzillaAdminPassword }}
  bugzilla-password: {{ default "" .Values.bugzillaAdminPassword | b64enc | quote }}
  {{- else }}
  bugzilla-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}